baseURL: https://andrewcloete.github.io/krux-web/
languageCode: en-us
title: Krux
theme: krux-hugo-theme
params:
  staticURL: https://github.com/AndrewCloete/krux-static/blob/master
  # staticURL: http://localhost:1313/krux-web
menu:
  main:
    - name: Blog
      url: blog
      weight: 1
    - name: What We Do
      url: what-we-do
      weight: 2
    - name: Courses
      url: courses
      weight: 3
    - name: Art Gallery
      url: gallery
      weight: 4
    - name: Meet the team
      url: team
      weight: 5
